[versions]
agp                         = "9.2.0"
android-compileSdk          = "37"
android-minSdk              = "26"
android-targetSdk           = "36"

kotlin                      = "2.3.20"
compose-multiplatform       = "1.9.0"
compose-ui-tooling          = "1.9.0"

androidx-activityCompose    = "1.13.0"
androidx-appcompat          = "1.7.1"
androidx-constraintlayout   = "2.2.1"
androidx-core-ktx           = "1.18.0"
androidx-espresso-core      = "3.7.0"
androidx-lifecycle          = "2.10.0"
androidx-test-junit         = "1.3.0"

compose-navigation          = "2.9.2"
components-resources        = "1.10.3"

ktor                        = "3.2.3"
coroutines                  = "1.9.0"
kotlinx-serialization       = "1.8.1"
kotlinx-datetime            = "0.8.0"

napier                      = "2.7.1"
inspektor                   = "0.3.9"
datastore                   = "1.2.1"
okio                        = "3.17.0"
firebase-bom                = "34.13.0"
koin                        = "4.2.1"

junit                       = "4.13.2"

[libraries]
kotlin-test                         = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit                   = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit                               = { group = "junit", name = "junit", version.ref = "junit" }
androidx-core-ktx                   = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-test-junit                 = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-junit" }
androidx-espresso-core              = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }
androidx-appcompat                  = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-constraintlayout           = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-activity-compose           = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-lifecycle-runtime-compose  = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
ktor-client-core                    = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp                  = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin                  = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-cio                     = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-client-auth                    = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-content-negotiation     = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
kotlinx-serialization-core          = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json          = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ktor-serialization-kotlinx-json     = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-logging                 = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
#ktor-client-timeout                = { group = "io.ktor", name = "ktor-client-timeout", version.ref = "ktor" }
kotlinx-coroutines-core             = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android          = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
navigation-compose                  = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "compose-navigation" }
compose-components-resources        = { module = "org.jetbrains.compose.components:components-resources", version.ref = "components-resources" }
napier                              = { module = "io.github.aakira:napier", version.ref = "napier" }
inspektor                           = { module = "com.gyanoba.inspektor:inspektor", version.ref = "inspektor" }
datastore-core                      = { module = "androidx.datastore:datastore", version.ref = "datastore" }
datastore-preferences               = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
okio                                = { module = "com.squareup.okio:okio", version.ref = "okio" }
kotlinx-datetime                    = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
firebase-bom                        = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-gcm                        = { module = "com.google.firebase:firebase-messaging" }
koin-core                           = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android                        = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose                        = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel              = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
compose-runtime                     = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-multiplatform" }
compose-foundation                  = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-multiplatform" }
compose-material3                   = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose-multiplatform" }
compose-ui                          = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose-multiplatform" }
compose-ui-tooling                  = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose-ui-tooling" }
compose-ui-tooling-preview          = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose-ui-tooling" }
compose-components-uiToolingPreview = { module = "org.jetbrains.compose.components:components-ui-tooling-preview", version.ref = "compose-multiplatform" }

[plugins]
androidApplication                  = { id = "com.android.application", version.ref = "agp" }
androidLibrary                      = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform                = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler                     = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform                 = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx-serialization               = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }